// Build-time translation keeps both languages on the same detector implementation.
const translations = {
'lang="ja"': 'lang="en"', 'ja-JP': 'en-US',
'超音波接近センサー': 'Acoustic Motion Sensor',
'PCを中心に、接近時は赤い波が内側へ、離反時は青い波が外側へ移動します': 'Red waves move toward the PC on approach; blue waves move outward on recession',
'Three.js 接近・離反の可視化': 'Three.js motion visualization',
'中心 = PC　·　波は動きの模式表示です。距離・位置・人数は測定しません。': 'Center = PC. Waves illustrate motion, not distance, position, or number of people.',
'測定を開始すると、周囲の動きを解析します。': 'Start sensing to analyze nearby motion.',
'PCスピーカーから高周波音を出し、マイクで反射音の変化を捉えます。': 'Emit a high-frequency tone and analyze changes in its reflections with your microphone.',
'出力：OS既定のスピーカー。ヘッドホンを外し、PC付近のスピーカーを使用してください。': 'Output: system default speakers. Disconnect headphones and use speakers near the PC.',
'超敏感：弱い変化が0.15秒続くと判定し、大きく表示します。音量は増やしません。環境音にも反応しやすいため、誤反応が多い場合は感度を下げてください。': 'Extra sensitive: detects weak changes sustained for 0.15 s and emphasizes the visualization. Output volume is unchanged. Lower sensitivity if background noise causes false detections.',
'デジタル振幅の設定です。実際の音圧ではありません。高音が聞こえる・不快な場合は停止してください。': 'Digital amplitude, not measured sound pressure. Stop if the tone is audible or uncomfortable.',
'通常約8秒。会話・一時的な物音は許容し、雑音の区間を除外して自動延長します。PCの位置は固定してください。': 'Usually about 8 seconds. Brief noise is excluded and calibration extends automatically. Keep the PC still.',
'音声はブラウザ内だけで処理し、録音・外部送信しません。人以外の動きにも反応します。静止した人の在席・防犯用途の保証はありません。画面を前面にして使用してください。': 'Audio is processed in your browser, never recorded or uploaded. Non-human motion can trigger detection. This is not a stationary-presence detector or a security system. Keep the page visible.',
'ブラウザのマイク使用許可を確認してください。': 'Allow microphone access in your browser.',
'発音前の高周波ノイズを測定しています。': 'Measuring high-frequency background noise before emitting the tone.',
'スピーカーからの高周波音をマイクで確認しています。': 'Checking whether the microphone receives the speaker tone.',
'一時的な音割れを除外し、送信音の確認を続けています。': 'Excluding brief clipping and continuing the tone check.',
'会話や一時的な物音は許容します。PCの位置を固定してお待ちください。': 'Conversation and brief sounds are tolerated. Keep the PC still while calibration completes.',
'雑音の区間を除外し、自動で安定した区間を追加しています。': 'Excluding noisy intervals and collecting more stable samples.',
'検知できる動きはありません。在席・不在を示すものではありません。': 'No detectable motion. This does not indicate presence or absence.',
'赤い波がPCへ向かって収束します。': 'Red waves converge toward the PC.',
'青い波がPCから外側へ広がります。': 'Blue waves expand outward from the PC.',
'接近・離反が混在しているか、方向を判定できません。': 'Motion is mixed or its direction cannot be determined.',
'入力・出力機器を確認して、再度開始してください。': 'Check the input and output devices, then start again.',
'送信音の低下を接近として検知しています。音量低下・消音でも反応します。': 'Tone attenuation is counted as approach or obstruction. Lowering or muting the volume can also trigger this.',
'校正完了。画面を前面にしたまま、PCに近づいて反応を確認してください。': 'Calibration complete. Keep this page visible and move near the PC to try sensing.',
'停止しました。発音とマイク入力を終了しています。': 'Stopped. Tone output and microphone input have ended.',
'マイクの使用が許可されていません。ブラウザのサイト設定を確認してください。': 'Microphone access was denied. Check the site permissions in your browser.',
'マイクが見つかりません。入力機器を接続してください。': 'No microphone found. Connect an input device.',
'通常約8秒。物音が入ると自動延長します。PCを固定してお待ちください。': 'Usually about 8 seconds; extends automatically for noise. Keep the PC still.',
'模擬音声を同じ解析器に入力しています。実際の接近検知ではありません。': 'Synthetic audio is processed by the same detector. This is not a real motion measurement.',
'デモ：実機の受信診断は行いません': 'Demo: hardware reception is not tested.',
'デモ：模擬音声を解析しています。マイク入力・スピーカー出力は使用していません。': 'Demo: analyzing synthetic audio. No microphone input or speaker output is used.',
'画面が非表示になったため停止しました。再度開始してください。': 'Stopped because the page became hidden. Start again to resume.',
'音声機器が変更されたため停止しました。再度開始してください。': 'Stopped because audio devices changed. Start again to resume.',
'3D非対応 · 数値とスペクトルで表示': '3D unavailable · metrics and spectrum remain active',
'3D停止 · ページを再読込': '3D stopped · reload the page',
'送信レベルは3%以下にしてください。感度は受信側で調整します。': 'Keep output level at or below 3%. Sensitivity is adjusted on the receiving side.',
'Chrome / Edge で localhost のページを開いてください。': 'Open this page over HTTPS or localhost in Chrome or Edge.',
'マイクから音声を取得できません。': 'Cannot receive microphone audio.',
'マイクの音声補正が有効です。補正を無効化できる入力機器を選んでください。': 'Microphone audio processing is enabled. Choose an input that allows processing to be disabled.',
'マイクが切断されました。': 'The microphone was disconnected.',
'マイク入力が一時停止しました。再開後に測定を開始してください。': 'Microphone input was interrupted. Start sensing again after it resumes.',
'音声処理が停止しました。測定を再開してください。': 'Audio processing stopped. Restart sensing.',
'解析が遅延しました。画面を前面にして再開してください。': 'Analysis stalled. Keep the page visible and restart sensing.',
'物音が続いて送信音を確認できません。少し落ち着いてから再度開始してください。': 'Persistent noise prevented tone qualification. Try again when the noise subsides.',
'20秒間、校正に必要な安定区間を集められませんでした。PC周辺の動きや高周波の妨害を減らして再度開始してください。': 'No stable calibration could be collected within 20 seconds. Reduce nearby motion or high-frequency interference and try again.',
'入力が音割れしています。マイク音量または送信レベルを下げてください。': 'Input is clipping. Lower microphone gain or output level.',
'送信音を確認できません（中央値受信 ': 'Tone qualification failed (median reception ',
'発音前後差 ': 'off/on rise ',
'dB）。必要条件は受信−75 dBFS以上・差10 dB以上です。スピーカー出力先・マイクを確認してください。': 'dB). Requires reception at least -75 dBFS and a rise of at least 10 dB. Check speaker output and microphone.',
'受信状態が変わりました。スピーカー・マイクの位置と音量を確認して再校正してください。': 'Reception changed. Check speaker and microphone positions and volume, then recalibrate.',
'このサンプルレートでは選択した周波数を解析できません。周波数を下げてください。': 'The selected frequency is not supported at this sample rate. Choose a lower frequency.',
'受信診断（瞬時）：': 'Reception (instantaneous): ', '（必要：受信−75 dBFS以上・上昇10 dB以上）': ' (required: at least -75 dBFS and 10 dB rise)',
'受信診断：送信音確認済み': 'Reception: tone qualified', '受信診断：発音前': 'Reception: before tone', '受信診断：マイクの準備中': 'Reception: preparing microphone', '受信診断：未測定': 'Reception: not measured',
'接近・遮蔽（受信低下）': 'Approach / obstruction (attenuation)', '接近・遮蔽を検知': 'Approach / obstruction detected',
'接近する動きを検知': 'Approaching motion detected', '離れる動きを検知': 'Receding motion detected', '周囲に動きを検知': 'Motion detected', '動き（方向不明）': 'Motion (direction unknown)',
'検知イベントはまだありません': 'No detection events yet', '検知イベント履歴': 'Detection history', 'デモ内のイベント': 'Demo events',
'送信周波数を中心とした受信スペクトル': 'Received spectrum centered on the emitted tone',
'物音を除外して校正中': 'Calibrating around noise', '物音の区間を除外中': 'Excluding noisy intervals', '環境音を確認中': 'Checking background noise', '送信音を確認中': 'Checking emitted tone', 'マイクを準備中': 'Preparing microphone', '周囲を校正中': 'Calibrating',
'測定コントロール': 'Sensing controls', 'システム既定のマイク': 'System default microphone', '入力マイク': 'Input microphone', '送信周波数': 'Tone frequency', '超敏感・大きく反応': 'Extra sensitive', '微弱・低速': 'Weak / slow', '送信レベル': 'Output level',
'測定を開始': 'Start sensing', 'デモを開始': 'Start demo', '測定できません': 'Unable to sense', 'マイク・発音なし': 'No mic or sound', '動きのデモ': 'Motion demo', 'デモの動き': 'Demo motion', '自動切替': 'Cycle', '微細な動き': 'Fine motion', '遮蔽・受信低下': 'Obstruction / attenuation',
'校正の進捗': 'Calibration progress', '受信スペクトル': 'Received spectrum', '検知状態': 'Detection status', '動きの強さ': 'Motion strength', '送信音の受信': 'Tone reception', '送信音の低下': 'tone attenuation', '校正基準超過': 'above baseline', '検知イベント': 'Detection events', '今回の測定': 'This session',
'接近する動き': 'Approaching motion', '離れる動き': 'Receding motion', '動きなし': 'No motion', '方向不明': 'Mixed / unknown', '離反側': 'receding', '接近側': 'approaching', '可聴の可能性': 'may be audible',
'待機中': 'Ready', '再校正': 'Recalibrate', '校正完了': 'Calibrated', '校正中': 'Calibrating', '模擬信号': 'Synthetic', '実測': 'Sensing', '待機': 'Ready', '上昇': 'rise', '感度': 'Sensitivity', '高い': 'High', '低い': 'Low', '標準': 'Standard', '停止': 'Stop', '接近': 'Approach', '離反': 'Recede', '静止': 'Still', '内側へ': 'inward', '外側へ': 'outward', '動き': 'Motion', '送信音': 'Tone', 'デモ': 'Demo', 'マイク ': 'Microphone ',
};
export function english(source) {
  for (const [ja, en] of Object.entries(translations).sort((a, b) => b[0].length - a[0].length)) source = source.split(ja).join(en);
  if (/[\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Han}]/u.test(source)) throw new Error('Untranslated Japanese in English output');
  return source;
}
